# Generated by Django 4.1.4 on 2022-12-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminsTG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(verbose_name='ID Telegram')),
                ('name', models.CharField(max_length=200, verbose_name='Имя администратора')),
            ],
            options={
                'verbose_name': 'Админа',
                'verbose_name_plural': 'Администраторы',
            },
        ),
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.BigIntegerField(verbose_name='ID канала')),
            ],
            options={
                'verbose_name': 'Канал',
                'verbose_name_plural': 'Каналы',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.IntegerField(default=1, editable=False, unique=True)),
                ('token', models.TextField(verbose_name='Токен бота')),
            ],
            options={
                'verbose_name': 'Токен',
                'verbose_name_plural': 'Токены',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(unique=True, verbose_name='ID Telegram')),
                ('username', models.CharField(max_length=150, null=True, verbose_name='Username')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='Имя')),
                ('competition_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID Участника')),
                ('fullname', models.CharField(max_length=250, null=True, verbose_name='Имя')),
                ('phone', models.CharField(max_length=250, null=True, verbose_name='Номер')),
                ('birth_day', models.DateField(null=True, verbose_name='День рождение')),
                ('ref_count', models.BigIntegerField(null=True, verbose_name='Рефералы')),
                ('parent', models.BigIntegerField(null=True, verbose_name='ID Пригласителя')),
                ('lang', models.CharField(max_length=250, null=True, verbose_name='Язык')),
                ('ban', models.BooleanField(default=True, verbose_name='Бан')),
            ],
            options={
                'verbose_name': 'Пользователя',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
