# Generated by Django 4.2.1 on 2023-05-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_botmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmessage',
            name='lang',
            field=models.CharField(choices=[('uz', 'Uz'), ('ru', 'Ru'), ('en', 'En')], default='ru', max_length=10),
        ),
    ]
