# Generated by Django 4.2.1 on 2023-06-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_botmessage_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminsTG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(verbose_name='ID Telegram')),
                ('name', models.CharField(max_length=200, verbose_name='Имя администратора')),
            ],
            options={
                'verbose_name': 'Админа',
                'verbose_name_plural': 'Администраторы',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.IntegerField(default=1, editable=False, unique=True)),
                ('token', models.TextField(verbose_name='Токен бота')),
                ('channel', models.BigIntegerField(verbose_name='ID канала')),
                ('contest', models.BooleanField(verbose_name='Активность конкурса')),
            ],
            options={
                'verbose_name': 'Токен',
                'verbose_name_plural': 'Токены',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(blank=True, unique=True, verbose_name='ID Telegram')),
                ('username', models.CharField(blank=True, max_length=150, null=True, verbose_name='Username')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя')),
                ('competition_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID Участника')),
                ('fullname', models.CharField(blank=True, max_length=250, null=True, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=250, null=True, verbose_name='Номер')),
                ('birth_day', models.DateField(blank=True, null=True, verbose_name='День рождение')),
                ('ref_count', models.BigIntegerField(blank=True, null=True, verbose_name='Рефералы')),
                ('parent', models.BigIntegerField(blank=True, null=True, verbose_name='ID Пригласителя')),
                ('lang', models.CharField(blank=True, max_length=250, null=True, verbose_name='Язык')),
                ('ban', models.BooleanField(blank=True, default=True, verbose_name='Бан')),
            ],
            options={
                'verbose_name': 'Пользователя',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
