# Generated by Django 4.2.18 on 2025-02-01 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_botmessage_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_id", models.BigIntegerField(verbose_name="ID канала")),
                (
                    "name",
                    models.CharField(max_length=250, verbose_name="Название канала"),
                ),
                (
                    "link",
                    models.CharField(max_length=250, verbose_name="Ссылка на канал"),
                ),
            ],
            options={
                "verbose_name": "Канал",
                "verbose_name_plural": "Каналы",
            },
        ),
        migrations.CreateModel(
            name="SubscribeRequests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_telegram_id",
                    models.BigIntegerField(verbose_name="ID Telegram"),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscribe_requests",
                        to="main.channel",
                        verbose_name="Канал",
                    ),
                ),
            ],
        ),
    ]
