# Generated by Django 4.2.18 on 2025-02-01 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_adminstg_token_user'),
        ('main', '0006_channel_subscriberequests'),
    ]

    operations = [
    ]
